def VERSION_SNAPSHOT_REPO_NAME = "thfai2000/version_snapshots"
def VERSION_SNAPSHOT_FOLDER_NAME = "sample-app"
def GIT_BRANCH = env.BRANCH_NAME
def ENV_CONFIG_GIT_SOURCE = 'https://github.com/thfai2000/sample-app-configuration.git'
def folderNames
def snapshotVersions

pipeline {
    agent any

    stages {

        stage('Checkout Env Config') {
            steps {
                dir('env-config') {

                    checkout([$class: 'GitSCM',
                            branches: [[name: env.BRANCH_NAME ]],
                            doGenerateSubmoduleConfigurations: false,
                            extensions: [],
                            submoduleCfg: [],
                            userRemoteConfigs: [[url: ENV_CONFIG_GIT_SOURCE]]])
                }
            }
        }

        stage('Input') {
            steps {
                dir('env-config') {
                    scripts {
                        folderNames = getFolderNames()
                        snapshotVersions = getSnapshotVersions()
                    }
                    input(message: 'Provide the build information',
                        ok: "Continue",
                        parameters: [
                            choice(name: 'WHICH_ENV', choices: folderNames, description: 'Select the environment'),
                            choice(name: 'VERSION_SNAPSHOT', choices: snapshotVersions, description: 'Select the snapshot version')
                        ]
                    )
                }
            }
        }
         stage('Loop through Artifacts') {
            steps {
                node {
                    def artifacts = readYaml(url: getSnapshotUrl(VERSION_SNAPSHOT))

                    for (def artifact in artifacts) {
                        stage("Artifact: ${artifact.name}") {
                            def targetFolder = sh(script: 'dirname $0', returnStdout: true).trim() + "/${params.WHICH_ENV}"
                            def hostYamlFiles = findFiles(glob: "${targetFolder}/hosts/*.yaml")

                            for (def hostYamlFile in hostYamlFiles) {
                                def hostYaml = readYaml(file: hostYamlFile.path)
                                def hostComponents = hostYaml.host_components

                                for (def component in hostComponents) {
                                    if (component.name == artifact.name) {
                                        echo "Artifact '${artifact.name}' found in Host YAML: ${hostYamlFile.name}"
                                    }
                                }
                            }
                        }
                    }
                }
            
            }
        }
        
    }
}


def getFolderNames() {
    
    // def currentDir = sh(script: 'pwd', returnStdout: true).trim()

    def folderList = sh(script: "ls -d | xargs -n 1 basename", returnStdout: true).trim().split('\n')
    return folderList
    
}

def getSnapshotVersions() {
    def gitSourceDirectory = '/path/to/git/source/directory' // Replace with your actual Git source directory
    def treeApiUrl = "https://api.github.com/repos/$VERSION_SNAPSHOT_REPO_NAME/contents/$VERSION_SNAPSHOT_FOLDER_NAME?ref=$GIT_BRANCH"
    
    def response = httpRequest(url: treeApiUrl, httpMode: 'GET', authentication: 'your_credentials')
    def fileNames = []
    if (response.status == 200) {
        def json = readJSON(text: response.content)
        fileNames = json.findAll { it.type == 'file' }.collect { it.name }
    }
    return fileNames
}

def getSnapshotUrl(version) {
    def gitSourceDirectory = '/path/to/git/source/directory' // Replace with your actual Git source directory
    def snapshotUrl = "https://raw.githubusercontent.com/$VERSION_SNAPSHOT_REPO_NAME/$GIT_BRANCH/$VERSION_SNAPSHOT_FOLDER_NAME/$version"
    return snapshotUrl
}