all: # keys must be unique, i.e. only one 'hosts' per group
    hosts:
    vars:
        global_var1: global_value
    children:   # key order does not matter, indentation does
        st:
            hosts:
            vars:
                which_site: st
            children:
                app:
                    hosts:
                        machine1:
                            ansible_host: machine1
                            test: m1
                    vars:
                        group_name: app
                web:
                    hosts:
                        machine2:
                            ansible_host: machine2
                            test: m2
                    vars:
                        group_name: web
        hv:
            hosts:
            vars:
                which_site: hv
            children:
                app:
                    hosts:
                        machine3:
                            ansible_host: machine3
                            test: m3
                    vars:
                        group_name: app
                web:
                    hosts:
                        machine4:
                            ansible_host: machine4
                            test: m4
                    vars:
                        group_name: web