---
- name: Download Artifacts
  hosts: "{{ target_hosts }}"
  tasks:
  - name: Gather Project Facts
    setup:
      filter: ansible_project_dir
  - name: Make folder
    file:
      path: artifacts
      state: directory
      mode: '0755'
  - name: Download Software Component Artifacts
    get_url:
      url: "{{ component_artifact_url }}"
      dest: artifacts/.
  - name: Transfer the Artifacts to target machine
    copy:
      src: artifacts/.
      dest: "{{ component_artifact_dest }}"
      mode: "0755"