---
- name: Stop component
  hosts: "{{ target_hosts }}"
  vars:
    target_component: "{{ component_name }}"
  tasks:
  - name: Execute tasks for component
    when: components is defined and target_component in components
    block:
    - name: Stop services
      become: true
      become_user: "{{ component_properties[component_name].component_service_account }}"
      ansible.builtin.shell: |
        {{ component_properties[component_name].component_stop_script }}
