---
- name: Stop component
  hosts: "{{ target_hosts }}"
  tasks:
    - name: Stop services
      become: true
      become_user: "{{component_service_account}}"
      ansible.builtin.shell: |
        {{ component_stop_script }}