def checkoutEnvConfig() {
    checkout([$class: 'GitSCM',
                branches: [[name: env.BRANCH_NAME]],
                doGenerateSubmoduleConfigurations: false,
                extensions: [],
                submoduleCfg: [],
                userRemoteConfigs: [[url: ENV_CONFIG_GIT_SOURCE]]])
    script {
        env.envNamesString = sh(script: "ls * | xargs -n 1 basename", returnStdout: true).trim()
    }
}

def checkoutAppSource() {
    checkout([$class: 'GitSCM',
                branches: [[name: env.BRANCH_NAME]],
                doGenerateSubmoduleConfigurations: false,
                extensions: [],
                submoduleCfg: [],
                userRemoteConfigs: [[url: APP_GIT_SOURCE]]])
}

def checkoutAnsibleSource() {
    checkout([$class: 'GitSCM',
                branches: [[name: env.BRANCH_NAME]],
                doGenerateSubmoduleConfigurations: false,
                extensions: [],
                submoduleCfg: [],
                userRemoteConfigs: [[url: ANSIBLE_GIT_SOURCE]]])
}

def selectEnv(closure){
    echo "GIT_BRANCH: ${env.BRANCH_NAME}"
    // echo "VERSION_SNAPSHOT_REPO_NAME: $VERSION_SNAPSHOT_REPO_NAME"
    dir('env-config') {
        checkoutEnvConfig()
    }
    dir('app-source') {
        checkoutAppSource()
    }
    dir('ansible-source'){
        checkoutAnsibleSource()
    }


    def envNames = env.envNamesString.split("\n")
    echo "type: ${envNames.getClass()}"
    echo "envNames: ${envNames}"
    
    def params = input(message: 'Provide the deployment information',
        ok: "Continue",
        parameters: [
            choice(name: 'which_env', choices: Arrays.asList(envNames), description: 'Select the environment')
        ]
    )
    if(closure){
        closure()
    }

    env.which_env = params.which_env
    echo "which_env=${env.which_env}"
}


def downloadComponent( componentName, componentVersion = 'spring24') {
    
    INVENTORY_DIR = 'env-config/ansible/inventory'
    PLAYBOOK_DIR = 'ansible-source/ansible/playbooks'

    sh """
    ansible-playbook -i ${INVENTORY_DIR}/common.yaml -i ${INVENTORY_DIR}/${env.which_env}.yaml  \
        --key-file "/home/jenkins/.ssh/id_rsa" \
        -e "target_hosts=${group}" \
        -e "component_version=${componentVersion}" \
       ${PLAYBOOK_DIR}/1-download-artifact.yaml
    """

}

def installComponent( componentName) {

    INVENTORY_DIR = 'env-config/ansible/inventory'

    sh """
    ansible-playbook -i ${INVENTORY_DIR}/common.yaml -i ${INVENTORY_DIR}/${env.which_env}.yaml  \
        --key-file "/home/jenkins/.ssh/id_rsa" \
        -e "target_hosts=${group}" \
        -e "component_version=${componentVersion}" \
        ${PLAYBOOK_DIR}/3-install-component.yaml
    """

}

def dbPatch( componentName) {
    sh """
    ansible "${componentName}" -i env-config/ansible/inventory/${env.which_env}.yaml --key-file "/home/jenkins/.ssh/id_rsa" -m command -a "echo 'dbPatch which_site={{ which_site }} group_name={{group_name}} test={{test}} '" 
    """

}

def stopComponent( componentName) {
    sh """
    ansible "${componentName}" -i env-config/ansible/inventory/${env.which_env}.yaml --key-file "/home/jenkins/.ssh/id_rsa" -m command -a "echo 'stopComponent which_site={{ which_site }} group_name={{group_name}} test={{test}} '" 
    """
}

def startComponent( componentName) {
    sh """
    ansible "${componentName}" -i env-config/ansible/inventory/${env.which_env}.yaml --key-file "/home/jenkins/.ssh/id_rsa" -m command -a "echo 'startComponent which_site={{ which_site }} group_name={{group_name}} test={{test}} '" 
    """
}

def healthCheckComponent( componentName) {
    sh """
    ansible "${componentName}" -i env-config/ansible/inventory/${env.which_env}.yaml --key-file "/home/jenkins/.ssh/id_rsa" -m command -a "echo 'healthCheckComponent which_site={{ which_site }} group_name={{group_name}} test={{test}} '" 
    """
}

pipeline {
    agent { label "ansible" }

    environment {
        ENV_CONFIG_GIT_SOURCE = 'https://github.com/thfai2000/sample-app-configuration.git'
        APP_GIT_SOURCE = 'https://github.com/thfai2000/sample-app.git'
        ANSIBLE_GIT_SOURCE = 'https://github.com/thfai2000/jenkins-pipelines.git'
    }

    stages {

        stage('Select Snapshot and Environment') {
            steps {
                selectEnv {
                }
            }
        }

        stage('Download Artifacts ') {
            parallel {
                stage('app') {
                    steps {
                        downloadComponent("app:&hv")
                        downloadComponent("app:&st")
                    }
                }
                stage('web') {
                    steps {
                        downloadComponent("web:&hv")
                        downloadComponent("web:&st")
                    }
                }
            }
        }
        
        stage('Stop & Install Components') {
            parallel {
                stage ("app") {
                    stages {
                        stage('stop') {
                            steps {
                                stopComponent("app")
                            }
                        }
                        stage('install') {
                            steps {
                                installComponent("app")
                            }
                        }
                    }
                }
                stage ("web") {
                    stages {
                        stage('stop') {
                            steps {
                                stopComponent("web")
                            }
                        }
                        stage('install') {
                            steps {
                                installComponent("web")
                            }
                        }
                    }
                }
            }
        }

        stage('Start Components') {
            parallel {
                stage('app') {
                    steps {
                        startComponent("app")
                    }
                }
                stage('web') {
                    steps {
                        startComponent("web")
                    }
                }
            }
        }

        stage('Health Check Components') {
            parallel {
                stage('app') {
                    steps {
                        healthCheckComponent("app") {
                        }
                    }
                }
                stage('web') {
                    steps {
                        healthCheckComponent("web") {
                        }
                    }
                }
            }
        }
    }
    post {
        always {
            echo "completed."
        }
    }
}


