def checkoutEnvConfig() {
    checkout([$class: 'GitSCM',
                branches: [[name: env.BRANCH_NAME]],
                doGenerateSubmoduleConfigurations: false,
                extensions: [],
                submoduleCfg: [],
                userRemoteConfigs: [[url: ENV_CONFIG_GIT_SOURCE]]])
    script {
        env.envNamesString = sh(script: "ls ansible/inventory/* | xargs -n 1 basename ", returnStdout: true).trim()
    }
}

def checkoutAppSource() {
    checkout([$class: 'GitSCM',
                branches: [[name: env.BRANCH_NAME]],
                doGenerateSubmoduleConfigurations: false,
                extensions: [],
                submoduleCfg: [],
                userRemoteConfigs: [[url: APP_GIT_SOURCE]]])
}

def checkoutAnsibleSource() {
    checkout([$class: 'GitSCM',
                branches: [[name: env.BRANCH_NAME]],
                doGenerateSubmoduleConfigurations: false,
                extensions: [],
                submoduleCfg: [],
                userRemoteConfigs: [[url: ANSIBLE_GIT_SOURCE]]])
}

def selectEnv(closure){
    echo "GIT_BRANCH: ${env.BRANCH_NAME}"
    // echo "VERSION_SNAPSHOT_REPO_NAME: $VERSION_SNAPSHOT_REPO_NAME"
    dir('env-config') {
        checkoutEnvConfig()
    }
    dir('app-source') {
        checkoutAppSource()
    }
    dir('ansible-source'){
        checkoutAnsibleSource()
    }


    def envNames = env.envNamesString.split("\n")
    echo "type: ${envNames.getClass()}"
    echo "envNames: ${envNames}"
    
    def params = input(message: 'Provide the deployment information',
        ok: "Continue",
        parameters: [
            choice(name: 'which_env', choices: Arrays.asList(envNames), description: 'Select the environment')
        ]
    )
    if(closure){
        closure()
    }
    echo "params=${params}"
    env.which_env = params
    echo "which_env=${env.which_env}"
}

def getComponentVersion( componentName ) {
    //TODO: make it find from a map
    return 'spring24'
}

def downloadComponent( hostPattern, components) {
    
    INVENTORY_DIR = 'env-config/ansible/inventory'
    PLAYBOOK_DIR = 'ansible-source/pipelines/ansible/playbooks'

    components.each { component ->
        sh """
        ansible-playbook -v -i ${INVENTORY_DIR}/common.yaml -i ${INVENTORY_DIR}/${env.which_env}  \
            --key-file "/home/jenkins/.ssh/id_rsa" \
            -e "target_hosts=${hostPattern}" \
            -e "component_name=${component}" \
            -e "component_version=${getComponentVersion(component)}" \
        ${PLAYBOOK_DIR}/1-download-artifact.yaml
        """
    }

}

def installComponent( hostPattern, components) {

    INVENTORY_DIR = 'env-config/ansible/inventory'
    PLAYBOOK_DIR = 'ansible-source/pipelines/ansible/playbooks'

    components.each { component ->
        sh """
        ansible-playbook -v -i ${INVENTORY_DIR}/common.yaml -i ${INVENTORY_DIR}/${env.which_env}  \
            --key-file "/home/jenkins/.ssh/id_rsa" \
            -e "target_hosts=${hostPattern}" \
            -e "component_name=${component}" \
            -e "component_version=${getComponentVersion(component)}" \
            ${PLAYBOOK_DIR}/3-install-component.yaml
        """
    }

}

// def dbPatch( hostPattern) {
//     sh """
//     ansible "${hostPattern}" -i env-config/ansible/inventory/${env.which_env} --key-file "/home/jenkins/.ssh/id_rsa" -m command -a "echo 'dbPatch which_site={{ which_site }} group_name={{group_name}} test={{test}} '" 
//     """

// }

def stopComponent( hostPattern, components) {

    INVENTORY_DIR = 'env-config/ansible/inventory'
    PLAYBOOK_DIR = 'ansible-source/pipelines/ansible/playbooks'

    components.each { component ->
        sh """
        ansible-playbook -v -i ${INVENTORY_DIR}/common.yaml -i ${INVENTORY_DIR}/${env.which_env}  \
            --key-file "/home/jenkins/.ssh/id_rsa" \
            -e "target_hosts=${hostPattern}" \
            -e "component_name=${component}" \
            -e "component_version=${getComponentVersion(component)}" \
            ${PLAYBOOK_DIR}/2-stop-component.yaml
        """
    }
}

def startComponent( hostPattern, components) {

    INVENTORY_DIR = 'env-config/ansible/inventory'
    PLAYBOOK_DIR = 'ansible-source/pipelines/ansible/playbooks'

    components.each { component ->
        sh """
        ansible-playbook -v -i ${INVENTORY_DIR}/common.yaml -i ${INVENTORY_DIR}/${env.which_env}  \
            --key-file "/home/jenkins/.ssh/id_rsa" \
            -e "target_hosts=${hostPattern}" \
            -e "component_name=${component}" \
            -e "component_version=${getComponentVersion(component)}" \
            ${PLAYBOOK_DIR}/4-start-component.yaml
        """
    }
}

def healthCheckComponent( hostPattern, components) {

    components.each { component ->
        sh """
        ansible "${hostPattern}" -i env-config/ansible/inventory/${env.which_env} --key-file "/home/jenkins/.ssh/id_rsa" -m command -a "echo 'healthCheckComponent which_site={{ which_site }} group_name={{group_name}} test={{test}} '" 
        """
    }
}

pipeline {
    agent { label "ansible" }

    environment {
        ENV_CONFIG_GIT_SOURCE = 'https://github.com/thfai2000/sample-app-configuration.git'
        APP_GIT_SOURCE = 'https://github.com/thfai2000/sample-app.git'
        ANSIBLE_GIT_SOURCE = 'https://github.com/thfai2000/jenkins-pipelines.git'
    }

    stages {
        
        stage('Select Snapshot and Environment') {
            steps {
                selectEnv {
                }
            }
        }

        stage('Download Artifacts ') {
            parallel {
                stage('frontend') {
                    steps {
                        downloadComponent("frontend:&hv", ['app','web'])
                        downloadComponent("frontend:&st", ['app','web'])
                    }
                }
                stage('backend') {
                    steps {
                        downloadComponent("backend:&hv",[])
                        downloadComponent("backend:&st",[])
                    }
                }
            }
        }
        
        stage('Rolling Install Components') {
            parallel {
                stage ("frontend") {
                    stages {
                        stage('stop+install hv') {
                            steps {
                                stopComponent("frontend:&hv", ['app','web'])
                                installComponent("frontend:&hv", ['app','web'])
                                startComponent("frontend:&hv", ['app','web'])
                                healthCheckComponent("frontend:&hv", ['app','web'])
                            }
                        }
                        stage('stop+install st') {
                            steps {
                                stopComponent("frontend:&st", ['app','web'])
                                installComponent("frontend:&st", ['app','web'])
                                startComponent("frontend:&st", ['app','web'])
                                healthCheckComponent("frontend:&st", ['app','web'])
                            }
                        }
                    }
                }
                stage ("backend") {
                    stages {
                        stage('stop+install hv') {
                            steps {
                                stopComponent("backend:&hv", [])
                                installComponent("backend:&hv", [])
                                startComponent("backend:&hv", [])
                                healthCheckComponent("backend:&hv", [])
                            }
                        }
                        stage('stop+install st') {
                            steps {
                                stopComponent("backend:&st", [])
                                installComponent("backend:&st", [])
                                startComponent("backend:&st",[])
                                healthCheckComponent("backend:&st",[])
                            }
                        }
                    }
                }
            }
        }
    }
    post {
        always {
            echo "completed."
        }
    }
}


