apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: sample-app-skaffold
build:
  artifacts:
    - image: thfai2000/sample-app
      kaniko:
        dockerfile: Dockerfile
  cluster:
    namespace: sample-app-skafford
    pullSecretName: kaniko-secret

manifests:
  rawYaml:
    - deployment.yaml
portForward:
  - resourceType: service
    resourceName: dockerfile-image
    port: 3000
