apiVersion: v1
kind: ConfigMap
metadata:
  name: nomad-config
data:
  nomad.hcl: |
    datacenter = "dc0"
    name = "nomad-on-k8s"

    data_dir  = "/opt/nomad/data"
    log_file = "/opt/nomad/log/nomad.log"
    log_level = "DEBUG"
    bind_addr = "0.0.0.0"

    client {
      enabled = true
      servers = ["172.31.65.45"]
    }
    plugin "docker" {
      config {
        endpoint = "tcp://127.0.0.1:2376"
        tls {
          cert = "/certs/client/cert.pem"
          key  = "/certs/client/key.pem"
          ca   = "/certs/client/ca.pem"
        }

      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nomad-dind-deployment
  labels:
    app: nomad-dind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nomad-dind
  template:
    metadata:
      labels:
        app: nomad-dind
    spec:
      containers:
        - name: nomad-agent
          image: thfai2000/nomad-docker:0.1
          securityContext:
            privileged: true
          ports:
            - containerPort: 4646
          command:
            - nomad
          args:
            - agent
            - -config=/opt/nomad/config/nomad.hcl  # Specify the config file
          # env:
          #   - name: DOCKER_HOST
          #     value: tcp://0.0.0.0:2376
          #   - name: DOCKER_TLS_VERIFY
          #     value: "1"
          #   - name: DOCKER_CERT_PATH
          #     value: /certs/client/
          volumeMounts:
            - name: nomad-data
              mountPath: /nomad/data
            - name: nomad-config
              mountPath: /opt/nomad/config  # Mount the ConfigMap
            - name: docker-certs
              mountPath: /certs
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
        - name: dind
          image: docker:19.03.12-dind
          env:
            - name: DOCKER_TLS_CERTDIR
              value: /certs
          securityContext:
            privileged: true
          volumeMounts:
            - name: dind-storage
              mountPath: /var/lib/docker
            - name: docker-certs
              mountPath: /certs
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "2"
      volumes:
        - name: docker-certs
          emptyDir: {}
        - name: nomad-data
          emptyDir: {}
        - name: dind-storage
          emptyDir: {}
        - name: nomad-config
          configMap:
            name: nomad-config 